// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaefvemksuxehxinfygq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZWZ2ZW1rc3V4ZWh4aW5meWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjAwMDQsImV4cCI6MjA3NDU5NjAwNH0.uWtCPkFivt5mXzAbqm6BpgKemv_3h2a3dy3GBW1VK9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});